name = "taxisatelital"
compatibility_date = "2025-08-24"

[build]
upload = { dir = "./dist" }

[assets]
directory = "./dist"

[env.production]
route = "www.taxisatelitalpremium.com.pe/*"
zone_id = "c9c753e71fb8159f5eeb64b2459a90ff"
